apiVersion: v1
kind: Service
metadata:
  name: node-services
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 31552