version: '3.9'

services:
  server:
    build: .
    ports:
      - '5001:5001'
    env_file:
      - /home/khaled/Desktop/Eheathpro_demo/backend/.env

  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'imeah'
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
